### ISSUE TITLE
[Bug/Crash] CTD when reloading (Mag redux)

### ISSUE THREAD

**Issue by big-clock** [ahuyn/anomaly-wpo#11]
When trying to reload, my game CTD. I get this error:

FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_error
[error]File          : ..\xrServerEntities\script_engine.cpp
[error]Line          : 191
[error]Description   : fatal error
[error]Arguments     : LUA error: .../stalker anomaly 1.5.1\gamedata\scripts\magazines.script:444: attempt to call field 'get_jammed' (a nil value)
 

I have Magazine Redux and BaS installed

**Comment by ahuyn** [comment]
Use latest wpo
