### ISSUE TITLE
Classic technician repair or allow technician to repair weapon parts request

### ISSUE THREAD

**Issue by daferret08** [ahuyn/anomaly-wpo#21]
Is it possible to re-enable classic repair at technicians as an MCM option so they repair the entire weapon (overall condition and parts)? I run with the Anomaly setting that repairs and upgrades by technicians take time and would like the techs to repair weapon parts while they "work on my weapon(s)".

**Comment by ahuyn** [comment]
Addressed in latest with multiple levels of service.
