### ISSUE TITLE
New version crash

### ISSUE THREAD

**Issue by bert-q** [ahuyn/anomaly-wpo#23]
After updating to the newest version (I used 1.11 prior to this) my game crashes when loading a save, and when I make a new game it crashes whenever I fire a weapon.  Does it have to do something with that i use BaS?

**New game error:**

! [LUA] SCRIPT RUNTIME ERROR
! [LUA] ...mes/anomaly-1.5.1.2\gamedata\scripts\arti_jamming.script:253: attempt to index global 'larp' (a nil value)
! [SCRIPT ERROR]: ...mes/anomaly-1.5.1.2\gamedata\scripts\arti_jamming.script:253: attempt to index global 'larp' (a nil value)
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_error
[error]File          : ..\xrServerEntities\script_engine.cpp
[error]Line          : 191
[error]Description   : fatal error
[error]Arguments     : LUA error: ...mes/anomaly-1.5.1.2\gamedata\scripts\arti_jamming.script:253: attempt to index global 'larp' (a nil value)

**Current save error:**

! [SCRIPT ERROR]: c:/games/anomaly-1.5.1.2\gamedata\scripts\wpo_loot.script:70: attempt to index global 'larp' (a nil value)
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_error
[error]File          : ..\xrServerEntities\script_engine.cpp
[error]Line          : 191
[error]Description   : fatal error
[error]Arguments     : LUA error: c:/games/anomaly-1.5.1.2\gamedata\scripts\wpo_loot.script:70: attempt to index global 'larp' (a nil value)

**Comment by ahuyn** [comment]
Copy this into your scripts: https://github.com/ahuyn/anomaly-dependencies/tree/8d52b057b8631351a631675affc39c6fcbeec8c8/larp/gamedata/scripts
This should have been added in the bundler.

**Comment by bert-q** [comment]
Alright thanks it worked.
