### ISSUE TITLE
Weapon permanently holstered if any other action is attempted during unjamming.

### ISSUE THREAD

**Issue by PDCWolf** [ahuyn/anomaly-wpo#26]
Hard to reproduce, but taking certain actions during the unjam animation (the gun being holstered) freezes the gun in a holstered position. No other gun can be equipped, knife can't be equipped either, but you can still open your PDA or get RF receiver/Detector.

This does not get fixed in any other way than reloading a save. I've tried unequipping, dropping, field stripping, unloading, and all possible inventory actions, along with all keystrokes (interact, reload, change ammunition, change fire mode, etc), and nothing brings back the affected or any other weapon.

Apparent steps:
Double tap F to fix a jam (doesn't seem to matter which kind)
Make another action - Attempting to swap weapons, draw knife, jump, interact with something via F
Gun is permanently holstered, you lose access to other guns.

**Comment by ahuyn** [comment]
This should be fixed in later iterations, having swapped the blocking holster for a nonblocking one.
