### ISSUE TITLE
Crash on part replacement

### ISSUE THREAD

**Issue by Coverdrave** [ahuyn/anomaly-wpo#27]
! [SCRIPT ERROR]: ...nomaly\gamedata\scripts\zzzz_arti_jamming_repairs.script:738: attempt to call global 'math_random' (a nil value)
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_error
[error]File          : ..\xrServerEntities\script_engine.cpp
[error]Line          : 191
[error]Description   : fatal error
[error]Arguments     : LUA error: ...nomaly\gamedata\scripts\zzzz_arti_jamming_repairs.script:738: attempt to call global 'math_random' (a nil value)
 

stack trace:

Apparently math_random isn't declared in the script like other math functions.

**Comment by ahuyn** [comment]
Fixed! Sorry
