### ISSUE TITLE
CTD when disassembling a wpn without a mag

### ISSUE THREAD

**Issue by ABYS501** [ahuyn/anomaly-wpo#35]
Stumbled upon a bug that crashes the game when i'm trying to disassemble a weapon that doesn't have a mag inside. Started happening after i updated WPO to the latest version (10.10.22). I use default wuut mags (version from the 18.02.21). Also, before update i used a version of WPO from around october/november of 2021.

weapon_eject_mag_precondition
weapon_eject_mag_precondition1
WeaponGetMagData: (wpn_ppsh41_woodnew) ID: 28136
WeaponGetMagData: (N:no_mag:0:)
WeaponGetMagData: (wpn_ppsh41_woodnew) ID: 28136
WeaponGetMagData: (N:no_mag:0:)
WeaponSetMagData N:no_mag:0:
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CInifile::r_section
[error]File          : Xr_ini.cpp
[error]Line          : 544
[error]Description   : fatal error
[error]Arguments     : Can't open section 'no_mag'.
 

stack trace:

**Comment by ahuyn** [comment]
Does this also happen when you eject a magazine?

**Comment by ABYS501** [comment]
No, ejecting a mag or disassembling a weapon with an attached mag works just fine. I was wondering, since i've been using the version from late 2021 this whole time, maybe this bug is somehow related to the removed defines.ltx dependency (as one of the major changes as i see it), but that's just shooting in the dark.

Tbh this one's not that bothersome cause you're almost always have a mag to a weapon you want to disassemble, but it's just weird it started happening when i haven't had any conflicts between WPO (and its previous versions) and wuut_mags all this time. Looks like WPO or some Anomaly scripts stopped recognising "no_mag" status of a weapon all of a sudden, if i get it right.

**Comment by ABYS501** [comment]
Also got the same error when tried to field strip a wpn with no mag attached. Doesn't matter if i do full or partial field strip - same error.
