### ISSUE TITLE
[Possible Bug] Weapon Condition Doesn't Go Up When Replacing Parts.

### ISSUE THREAD

**Issue by ACluelessFool** [ahuyn/anomaly-wpo#7]
**Addon Version:** Latest Release - October 14th
**Other Relevant Addons:** 
- Outfit Parts and Repair Overhaul + WPO patch, using the Github latest release
- Mechanics Can Repair Weapon Parts by _anomalu_, https://www.moddb.com/mods/stalker-anomaly/addons/mechanics-can-repair-weapon-parts
---
Encountered Problem: So I may have ran into a possible bug (or incompatibility?) where the weapon's condition doesn't adjust accordingly when I replace broken parts from the workbench. 

As far as I understand it, weapon condition is the overall _cleanliness_ of the gun, right? And because the gun I was repairing, the TOZ-34 Bizon, was at critical condition with 5% and all of its parts broken, I thought that its condition would go up as I replace its broken parts with _clean_ and refurbished parts (thanks to MCRWP linked above). 

However, the shotgun stayed at 5% despite me having replaced all of its broken components at Xenotech's workbench. I used the shotgun repair kit itself to raise the condition and that's when more weirder stuff happened. The kit started to, as stated in the mod description, replace the "damaged" parts, even though I just replaced them with fresh ones, and generated two 0% shotgun parts that it had replaced. 

I'm hoping you might have some insight into this unless I was interpreting the mod's functions wrong. And I do apologies for not having any images or videos since I wasn't doing any recording when I ran into that problem.

EDIT: Forgot to mention that I did load up the addon and the other related addons to active save - after I obtained the near broken TOZ-34 Bizon.

**Comment by BeastPC47** [comment]
Exactly the same problem, I repaired parts of the gun from the BAS mod, but when installing the repaired part, the condition of the weapon worsened, and this was due to one part, the rest of the parts were installed without problems. Sorry for the grammar, I used a translator.

**Comment by BeastPC47** [comment]
On the version from 2022 01 08 it works fine.

**Comment by BeastPC47** [comment]
It turns out not, on version 1. 08.2022 exactly the same problem.
