### ISSUE TITLE
[Bug/Crash] a_wpo_parts.script, Line 20; script attempted to index weapon parts of a knife

### ISSUE THREAD

**Issue by ACluelessFool** [ahuyn/anomaly-wpo#8]
**Addon Version:** October 31st, 2021 Release
**Full Modlist:** [MO2 Modlist 2021.8.11.txt](https://github.com/ahuyn/anomaly-wpo/files/7498858/MO2.Modlist.2021.8.11.txt)

----

**Problem and Details:** Interesting game crash when I tried to transition from Rostok to Army Warehouses and from Dead City to Limansk. It doesn't occur again when I load up from the autosave, however. Here's the bug report clipped from my log:

```
Checking parts for wpn_knife3

! [SCRIPT ERROR]: ...nomaly/anomaly 1.5.1\gamedata\scripts\a_wpo_parts.script:20: attempt to index a nil value
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_error
[error]File          : ..\xrServerEntities\script_engine.cpp
[error]Line          : 191
[error]Description   : fatal error
[error]Arguments     : LUA error: ...nomaly/anomaly 1.5.1\gamedata\scripts\a_wpo_parts.script:20: attempt to index a nil value
 

stack trace:
```

I checked the script itself (and as far as I can tell, I have no other mod that overrides the script) and it appears that - from my amatuer understanding of Lua - the game is trying to obtain data from my hunting knife, which lacks the appropriate data for the script to pull from, which I assume is the components of the weapon.

Hope this report doesn't cause any problem or frustration on your end, just want to bring it up since its been rather semi-frequent since the latest release.

**Comment by ahuyn** [comment]
Wasn't your hunting knife it looks like - must have been some other item that didn't get caught. Let me see, I have some ideas

**Comment by ahuyn** [comment]
Please pull latest, I added a check

**Comment by ACluelessFool** [comment]
> Please pull latest, I added a check

Its late and I'm heading to sleep, but I'll be sure to download the latest by morning! Thanks for responding man.

**Comment by ACluelessFool** [comment]
Alright. Latest update seems to be nice and tight. No crashes as of now. Thank you for responding Ahuyn!
